/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ItemsIdRouteImport } from './routes/items/$id'
import { Route as ItemsTagsTagRouteImport } from './routes/items/tags/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsTagsTagRoute = ItemsTagsTagRouteImport.update({
  id: '/items/tags/$tag',
  path: '/items/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/': typeof ItemsIndexRoute
  '/items/tags/$tag': typeof ItemsTagsTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items/$id': typeof ItemsIdRoute
  '/items': typeof ItemsIndexRoute
  '/items/tags/$tag': typeof ItemsTagsTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/': typeof ItemsIndexRoute
  '/items/tags/$tag': typeof ItemsTagsTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items/$id' | '/items/' | '/items/tags/$tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items/$id' | '/items' | '/items/tags/$tag'
  id: '__root__' | '/' | '/items/$id' | '/items/' | '/items/tags/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  ItemsTagsTagRoute: typeof ItemsTagsTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/tags/$tag': {
      id: '/items/tags/$tag'
      path: '/items/tags/$tag'
      fullPath: '/items/tags/$tag'
      preLoaderRoute: typeof ItemsTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsIdRoute: ItemsIdRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  ItemsTagsTagRoute: ItemsTagsTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
